# Generated by Django 5.1.4 on 2025-01-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='NamaAkhir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guru',
            name='NamaTengah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
