# Generated by Django 5.1.4 on 2025-01-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_guru_namaakhir_alter_guru_namatengah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namamapel',
            name='KodeMapel',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='namamapel',
            name='Mapel',
            field=models.CharField(max_length=50),
        ),
    ]
